updated Route to get rid of error:
/Users/ulises.rey/local_code/UOC/OOP/OOP_PR/LocUOComotive/src/main/java/edu/uoc/locuocomotive/model/Model.java:80: error: constructor Route in class Route cannot be applied to given types;
                Route route = new Route(values[0], train, routeStations, schedules);
                              ^
  required: String,int,List<StationSchedule>
  found:    String,Train,List<Station>,Map<Station,List<Schedule>>
  reason: actual and formal argument lists differ in length